grpc_port: 6060
grpc_host: localhost

Postgres:
  postgres_host: ${POSTGRES_HOST}
  postgres_port: ${POSTGRES_PORT}
  postgres_db: ${POSTGRES_DB}
  postgres_user: ${POSTGRES_USER}
  postgres_password: ${POSTGRES_PASSWORD}