grpc_port: 6060
grpc_host: 0.0.0.0

model1_tokenizer_path: /app/internal/modelWrapper/data/rubert-tiny2-russian-sentiment-onnx/tokenizer.json
model1_model_path: /app/internal/modelWrapper/data/rubert-tiny2-russian-sentiment-onnx/model.onnx
model1_output_size: 3
model1_batch_size: 2

model2_tokenizer_path: /app/internal/modelWrapper/data/rubert-tiny2-russian-emotion-detection-ru-go-emotions/tokenizer.json
model2_model_path: /app/internal/modelWrapper/data/rubert-tiny2-russian-emotion-detection-ru-go-emotions/model.onnx
model2_output_size: 28
model2_batch_size: 2