grpc_port: 6060
grpc_host: 0.0.0.0
batch_timeout: 50
timeout : 5

models:
  - name: "russian-sentiment"
    tokenizer_path: "/home/smooth/Рабочий стол/ServingML/internal/modelWrapper/data/rubert-tiny2-russian-sentiment-onnx/tokenizer.json"
    model_path: "/home/smooth/Рабочий стол/ServingML/internal/modelWrapper/data/rubert-tiny2-russian-sentiment-onnx/model.onnx"
    input_size: 1
    output_size: 3
    batch_size: 4

  - name: "emotion-detection"
    tokenizer_path: "/home/smooth/Рабочий стол/ServingML/internal/modelWrapper/data/rubert-tiny2-russian-emotion-detection-ru-go-emotions/tokenizer.json"
    model_path: "/home/smooth/Рабочий стол/ServingML/internal/modelWrapper/data/rubert-tiny2-russian-emotion-detection-ru-go-emotions/model.onnx"
    input_size: 1
    output_size: 28
    batch_size: 4